import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme/theme-provider"
import { ClerkProvider } from "@clerk/nextjs";
import ReactQueryProvider from "@/react-query";
import { ReduxProvider } from "@/redux/provider";
import { Toaster } from "sonner";
const manrope = DM_Sans({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${manrope.className} bg-[#171717]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          >
            <ReduxProvider>
          <ReactQueryProvider>
          {children}
          <Toaster/>
          </ReactQueryProvider>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
